<?php
    $layout = "layouts/layout_login";
    $layoutParams['pageTitle'] = "Login";
?>

<form action="/admin/login" method="post">

    <h1>Login Admin</h1>

    <div class="container">
        <label for="email"><b>Nome</b></label>
        <input type="email" placeholder="Digite seu Email" name="email" required>

        <label for="password"><b>Senha</b></label>
        <input type="password" placeholder="Digite sua Senha" name="password" required>
            
        <button type="submit">Login</button>
    </div>

</form>