<?php
    $layout = "layouts/layout_admin";
    $layoutParams['pageTitle'] = "Novo Usuário";
?>
<h1><?=$layoutParams['pageTitle']?></h1>

<form method="post">

    <div class="form-content">
        <label for="email"><b>Email</b></label>
        <input type="email" name="email" required>

        <label for="senha"><b>Senha</b></label>
        <input type="password" name="senha" required>

            
        <button type="submit">Gravar</button>
    </div>

</form>