<?php
    $layout = "layouts/layout_admin";
    $layoutParams['pageTitle'] = "Novo Produto";
?>
<h1><?=$layoutParams['pageTitle']?></h1>

<form method="post" enctype="multipart/form-data">

    <div class="form-content">
        <label for="nome">Nome</label>
        <input type="text" id="nome" name="nome" required>

        <label for="descricao">Descrição</label>
        <textarea id="descricao" name="descricao" rows="4" cols="50"></textarea>

        <label for="marca">Marca</label>
        <select id="marca" name="marca" required>
            <option value="" disabled selected>Selecione a marca</option>
            <?php foreach($marcas as $marca): ?>
                <option value="<?=$marca->id?>"><?=$marca->nome_marca?></option>
            <?php endforeach;?>
        </select>

        <label for="categoria">Categoria</label>
        <select id="categoria" name="categoria" required>
            <option value="" disabled selected>Selecione a categoria</option>
            <?php foreach($categorias as $categoria): ?>
                <option value="<?=$categoria->id?>"><?=$categoria->nome_categoria?></option>
            <?php endforeach;?>
        </select>

        <label for="valor">Valor</label>
        <input type="number" step="0.01" min="0" id="valor" name="valor" required>

        <label for="desconto">Desconto</label>
        <input type="number" step="0.01" min="0" id="desconto" name="desconto" required>

        <label for="diponivel">Total Disponivel</label>
        <input type="number" min="0" id="diponivel" name="diponivel" required>

        <label for="imagem">Imagem:</label>
        <input type="file" id="imagem" name="imagem" required>

            
        <button type="submit">Gravar</button>
    </div>

</form>