<?php
    $layout = "layouts/layout_site";
    $layoutParams['pageTitle'] = "Checkout";
    $total = 0;
?>


<div class="col-md-12">
    <h1 class="text-center my-5">Checkout</h1>

    <div class="row">

        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Pagamento
                </div>
                <div class="card-body">
                    <div class="col-md-5 mb-3">
                    <label for="country">Forma Pagamento</label>
                    <select class="custom-select d-block w-100" id="country" required="">
                        <option selected disabled>Selecione...</option>
                        <option value="0">Boleto</option>
                    </select>
                </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <table class="table table-bordered">
                <thead>
                    <th>Produto</th>
                    <th>Valor</th>
                </thead>
                <tbody>
                    <?php 
                        foreach($produtos as $produto): 
                            $quantidade = $carrinho[$produto->id]['qtd'];
                            $valor = $quantidade * $produto->valor_preco;
                            $total += $valor;
                    ?>
                            <tr>
                                <td><?=$produto->nome_chocolate?></td>
                                <td><?=number_format($valor,2,',','.')?></td>
                            </tr>
                        <?php endforeach;?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Total</th>
                        <td><?=number_format($total,2,',','.')?></td>
                    </tr>
                </tfoot>
            </table>
            <div class="my-5">
                <a href="/checkout/finalizar" class="btn btn-lg btn-block btn-success text-uppercase">Finalizar</a>
            </div>
        </div>
    </div>
</div>

<div class="col mb-2">
    <div class="row">

    </div>
</div>


