<?php
    $layout = "layouts/layout_site";
    $layoutParams['pageTitle'] = "Conta Cliente";
?>



<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-dark navbar-dark sidebar collapse">
    <div class="sidebar-sticky pt-3">
    <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#dados">Meus Dados</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#carrinho">Carrinho</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#pedidos">Meus Pedidos</a>
            </li>

        </ul>
    </div>
</nav>

<div class="col-md-9 ml-sm-auto col-lg-10 px-md-4 py-4">

</div>