<?php
    $layout = "layouts/layout_site";
    $layoutParams['pageTitle'] = "Pagina Inicial";
?>


<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-dark navbar-dark sidebar collapse">
    <div class="sidebar-sticky pt-3">
    <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#recentes">Recentes</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#promocoes">Promoções</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    Categorias
                </a>
                <div class="dropdown-menu">
                    <?php foreach($categorias as $categoria): ?>
                        <a class="dropdown-item" href="#<?=$categoria->id?>"><?=$categoria->nome_categoria?></a>
                    <?php endforeach; ?>
                </div>
            </li>    
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    Marcas
                </a>
                <div class="dropdown-menu">
                    <?php foreach($marcas as $marca): ?>
                        <a class="dropdown-item" href="#<?=$marca->id?>"><?=$marca->nome_marca?></a>
                    <?php endforeach; ?>
                </div>
            </li>
        </ul>
    </div>
</nav>

<div class="col-md-9 ml-sm-auto col-lg-10 px-md-4 py-4">
    <div class="row" id="produtos">
        <?php foreach($produtos as $produto): ?>
            <div class="col-md-3 mb-5">
                <div class="card">
                    <img class="card-img-top" src="<?=$produto->imagem?>" alt="Imagem produto">
                    <div class="card-body">
                        <h4 class="card-title"><?=$produto->nome_chocolate?></h4>
                        <p class="card-text"><?=$produto->desc_chocolate?></p>
                        <a href="#visualizar">Ver mais</a>
                    </div>
                    <div class="card-footer">
                        <form action="/carrinho/add" method="POST">
                            <input type="hidden" name="produto_id" value="<?=$produto->id?>">
                            <button type="submit" class="btn btn-sm btn-success">Comprar <i class="fas fa-cart-plus"></i></button>
                            <div class="float-right">
                                R$ <?=number_format($produto->valor_preco, 2, ',', '.')?>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
