<?php
    $pageTitle = $pageTitle ?? 'Login';
?>
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title><?=$pageTitle?></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSS -->
        <link rel="stylesheet" href="/Resources/css/common.css">
        <link rel="stylesheet" href="/Resources/css/login.css">
    </head>
    <body>

        <div class="content center">
            <?= $body ?>
        </div>

    </body>
</html>