<?php
    $pageTitle = $pageTitle ?? 'Admin';
?>
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title><?=$pageTitle?></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSS -->
        <link rel="stylesheet" href="/Resources/css/common.css">
        <link rel="stylesheet" href="/Resources/css/admin.css">
    </head>
    <body>
        <div class="sidenav">
            <a href="/admin">Dashboard</a>
            <a href="/admin/categorias">Categorias</a>
            <a href="/admin/marcas">Marcas</a>
            <a href="/admin/produtos">Produtos</a>
            <a href="/admin/pedidos">Pedidos</a>
            <a href="/admin/usuarios">Usuários</a>
            <a href="/admin/logout">Logout</a>
        </div>

        <div class="content">
            <?= $body ?>
        </div>

    </body>
</html>